apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: jz0cgbcjt-nodejs 
  janus-idp.io/tekton: jz0cgbcjt-nodejs
  backstage.io/kubernetes-id: jz0cgbcjt-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jz0cgbcjt-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  