apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jz0cgbcjt-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jz0cgbcjt-nodejs 
  name: jz0cgbcjt-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: jz0cgbcjt-nodejs 
